# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Check quality on pull request

on:
  pull_request:
    branches: main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout version
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Jest Test with Coverage
        run: npm run test:coverage

      - name: Run all linters (ESLint, Stylelint)
        run: npm run lint

      - name: Build Storybook Documentation
        run: npm run build-storybook

      - name: Check if version is modified since last commit
        uses: EndBug/version-check@v2

      - name: If version unchanged
        if: steps.check.outputs.changed == 'false'
        run: exit 1
