# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NPM Package

on:
  push:
    branches:
      - main

jobs:
  # test > lint > build doc > build component > update version > deploy (npm)
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout version
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run all linters (ESLint, Stylelint)
        run: npm run lint

      - name: Build Storybook Documentation
        run: npm run build-storybook

      - name: Deploy Storybook Documentation to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: storybook-static

      - name: Deploy to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
